# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crew_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='crew_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63rew_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n\x17\x44\x61teTimeLocationRequest\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x30\n\x0c\x64\x65parture_dt\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\treturn_dt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"!\n\rPilotResponse\x12\x10\n\x08pilot_id\x18\x01 \x01(\t\"\xbb\x01\n\"PilotLocationDatetimePeriodRequest\x12\x10\n\x08pilot_id\x18\x01 \x01(\t\x12\x15\n\x08location\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x30\n\x0c\x64\x65parture_dt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\treturn_dt\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0b\n\t_location\".\n\x1cScheduleConfirmationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa3\x01\n\x0b\x43rewService\x12\x39\n\x0bGetPilotFor\x12\x18.DateTimeLocationRequest\x1a\x0e.PilotResponse\"\x00\x12Y\n\x11ScheduleFlightFor\x12#.PilotLocationDatetimePeriodRequest\x1a\x1d.ScheduleConfirmationResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_DATETIMELOCATIONREQUEST = _descriptor.Descriptor(
  name='DateTimeLocationRequest',
  full_name='DateTimeLocationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='DateTimeLocationRequest.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='departure_dt', full_name='DateTimeLocationRequest.departure_dt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='return_dt', full_name='DateTimeLocationRequest.return_dt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=196,
)


_PILOTRESPONSE = _descriptor.Descriptor(
  name='PilotResponse',
  full_name='PilotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pilot_id', full_name='PilotResponse.pilot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=231,
)


_PILOTLOCATIONDATETIMEPERIODREQUEST = _descriptor.Descriptor(
  name='PilotLocationDatetimePeriodRequest',
  full_name='PilotLocationDatetimePeriodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pilot_id', full_name='PilotLocationDatetimePeriodRequest.pilot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='PilotLocationDatetimePeriodRequest.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='departure_dt', full_name='PilotLocationDatetimePeriodRequest.departure_dt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='return_dt', full_name='PilotLocationDatetimePeriodRequest.return_dt', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_location', full_name='PilotLocationDatetimePeriodRequest._location',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=234,
  serialized_end=421,
)


_SCHEDULECONFIRMATIONRESPONSE = _descriptor.Descriptor(
  name='ScheduleConfirmationResponse',
  full_name='ScheduleConfirmationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ScheduleConfirmationResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=469,
)

_DATETIMELOCATIONREQUEST.fields_by_name['departure_dt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATETIMELOCATIONREQUEST.fields_by_name['return_dt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PILOTLOCATIONDATETIMEPERIODREQUEST.fields_by_name['departure_dt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PILOTLOCATIONDATETIMEPERIODREQUEST.fields_by_name['return_dt'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PILOTLOCATIONDATETIMEPERIODREQUEST.oneofs_by_name['_location'].fields.append(
  _PILOTLOCATIONDATETIMEPERIODREQUEST.fields_by_name['location'])
_PILOTLOCATIONDATETIMEPERIODREQUEST.fields_by_name['location'].containing_oneof = _PILOTLOCATIONDATETIMEPERIODREQUEST.oneofs_by_name['_location']
DESCRIPTOR.message_types_by_name['DateTimeLocationRequest'] = _DATETIMELOCATIONREQUEST
DESCRIPTOR.message_types_by_name['PilotResponse'] = _PILOTRESPONSE
DESCRIPTOR.message_types_by_name['PilotLocationDatetimePeriodRequest'] = _PILOTLOCATIONDATETIMEPERIODREQUEST
DESCRIPTOR.message_types_by_name['ScheduleConfirmationResponse'] = _SCHEDULECONFIRMATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DateTimeLocationRequest = _reflection.GeneratedProtocolMessageType('DateTimeLocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATETIMELOCATIONREQUEST,
  '__module__' : 'crew_service_pb2'
  # @@protoc_insertion_point(class_scope:DateTimeLocationRequest)
  })
_sym_db.RegisterMessage(DateTimeLocationRequest)

PilotResponse = _reflection.GeneratedProtocolMessageType('PilotResponse', (_message.Message,), {
  'DESCRIPTOR' : _PILOTRESPONSE,
  '__module__' : 'crew_service_pb2'
  # @@protoc_insertion_point(class_scope:PilotResponse)
  })
_sym_db.RegisterMessage(PilotResponse)

PilotLocationDatetimePeriodRequest = _reflection.GeneratedProtocolMessageType('PilotLocationDatetimePeriodRequest', (_message.Message,), {
  'DESCRIPTOR' : _PILOTLOCATIONDATETIMEPERIODREQUEST,
  '__module__' : 'crew_service_pb2'
  # @@protoc_insertion_point(class_scope:PilotLocationDatetimePeriodRequest)
  })
_sym_db.RegisterMessage(PilotLocationDatetimePeriodRequest)

ScheduleConfirmationResponse = _reflection.GeneratedProtocolMessageType('ScheduleConfirmationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULECONFIRMATIONRESPONSE,
  '__module__' : 'crew_service_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleConfirmationResponse)
  })
_sym_db.RegisterMessage(ScheduleConfirmationResponse)



_CREWSERVICE = _descriptor.ServiceDescriptor(
  name='CrewService',
  full_name='CrewService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=472,
  serialized_end=635,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPilotFor',
    full_name='CrewService.GetPilotFor',
    index=0,
    containing_service=None,
    input_type=_DATETIMELOCATIONREQUEST,
    output_type=_PILOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ScheduleFlightFor',
    full_name='CrewService.ScheduleFlightFor',
    index=1,
    containing_service=None,
    input_type=_PILOTLOCATIONDATETIMEPERIODREQUEST,
    output_type=_SCHEDULECONFIRMATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREWSERVICE)

DESCRIPTOR.services_by_name['CrewService'] = _CREWSERVICE

# @@protoc_insertion_point(module_scope)
