# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crew_service_pb2 as crew__service__pb2


class CrewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPilotFor = channel.unary_unary(
                '/CrewService/GetPilotFor',
                request_serializer=crew__service__pb2.DateTimeLocationRequest.SerializeToString,
                response_deserializer=crew__service__pb2.PilotResponse.FromString,
                )
        self.ScheduleFlightFor = channel.unary_unary(
                '/CrewService/ScheduleFlightFor',
                request_serializer=crew__service__pb2.PilotLocationDatetimePeriodRequest.SerializeToString,
                response_deserializer=crew__service__pb2.ScheduleConfirmationResponse.FromString,
                )


class CrewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPilotFor(self, request, context):
        """Get single available pilot for given datetime and location request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleFlightFor(self, request, context):
        """Schedule a flight for the given Pilot and datetime period
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPilotFor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPilotFor,
                    request_deserializer=crew__service__pb2.DateTimeLocationRequest.FromString,
                    response_serializer=crew__service__pb2.PilotResponse.SerializeToString,
            ),
            'ScheduleFlightFor': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleFlightFor,
                    request_deserializer=crew__service__pb2.PilotLocationDatetimePeriodRequest.FromString,
                    response_serializer=crew__service__pb2.ScheduleConfirmationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CrewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPilotFor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrewService/GetPilotFor',
            crew__service__pb2.DateTimeLocationRequest.SerializeToString,
            crew__service__pb2.PilotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScheduleFlightFor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CrewService/ScheduleFlightFor',
            crew__service__pb2.PilotLocationDatetimePeriodRequest.SerializeToString,
            crew__service__pb2.ScheduleConfirmationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
